### ISSUE TITLE
publish sdist to pypi

### ISSUE THREAD

**Issue by chenrui333** [unioslo/zabbix-cli#197]
👋 it would be good to also publish the sdist to pypi, thanks!

**Comment by pederhan** [comment]
As noted in the README, we are in the process of acquiring the name _zabbixcli_ on PyPI. PyPI does not allow us to publish  _zabbix-cli_, since its name is too similar. We cannot publish it under that name until we own the inactive _zabbixcli_ project or it is deleted. We have submitted a PEP 541 request for that here: https://github.com/pypi/support/issues/4655

I can look into making an aliased package if there is enough interest, but it's not a priority right now.

**Comment by pederhan** [comment]
You can now install the application with:

```
pip install zabbix-cli-uio
```

The application is still invoked with:

```
zabbix-cli
```
